apiVersion: apps/v1
kind: Deployment
metadata:
  name: decase-ai
  namespace: sk-team-08
spec:
  replicas: 2
  selector:
    matchLabels:
      app: decase-ai
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 41ea7741d6ea2b0a77eb2c75861ae389
      labels:
        app: decase-ai
    spec:
      containers:
      - name: decase-ai
        image: amdp-registry.skala-ai.com/skala25a/sk-team-08-decase-ai:1.0.0-16-6b48b652645f
        imagePullPolicy: Always
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: USER_NAME
          value: sk-team-08
        - name: NAMESPACE
          value: sk-team-08
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secret
              key: OPENAI_API_KEY